/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 * com.ferra13671.cometrenderer.minecraft.RenderColor
 * org.joml.Vector2i
 */
package com.ferra13671.bthack;

import com.ferra13671.bthack.BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV;
import com.ferra13671.cometrenderer.minecraft.RenderColor;
import org.joml.Vector2i;

public final class ItemUtils {
 public static final RenderColor yQgyRbzvArWXVsfxUvs_YEpFdAefcNVK;
 public static final Vector2i NzqAeWuhxaEZfyWgCRKAyEUisjcGiStq;
 public static final int PVOIdrmIXYWHrYrQMvVPyDfCHcmlyTNO = 2;
 public static final int nETkVlEMCHiCdK_mQDOclnydGfdgpbkU = 20;
 public static final RenderColor qLGiNZguIVWuYgukYQCVPuudbcUtMGCl;
 public static final RenderColor zmVUyjYbuHQxDLnBwb_hxxL_kvTnlMma;
 public static final int jPMGZbooFJiTXSXwBwPeRXNtVyTatRHK = 35;
 public static final RenderColor kUeBudAektqsoWQaBmyIysBZrmaXRpRf;
 public static final RenderColor FoDFGMKsINYoeIDPZYrCXxCwrIuuKtWj;
 public static final Vector2i xdAkggrqt_LXsmGOYIajCAYEaOZesRtP;
 public static final Vector2i TlqtoNNKbxBkzVvoNoaZUpYppoJpOlaX;
 public static final int nKGTavpcBzMjNwsEhBVTDS_CgyUhBXIi = 12;
 public static final ItemFilter m_sEbXCcekDevArDsotSNehErhobVWHN;
 public static final Vector2i tgJLPLRmNFSHcOjOrKFlKiCzMikowIOX;
 public static final int ExKZLBGmJ_bMsCgmZwVoGuTBSyvocvHU = 18;
 public static final Vector2i DFUWuaUujKjcvOENqGVMLjZiFBolTTYs;
 public static final int AMQZRxYObWVbPJEmWFPT_mbJHNpFugmX = 18;
 public static final ItemFilter ctKTNGRtdSZideKETtxhftLMUGSisMoI;
 public static final ItemFilter IyJncuwtlZNSFuDfXhQZURvAWjfa_PzS;
 public static final ItemFilter a_lbOGSpCqNmwKlKXuzrovwerhFbmOyH;
 public static final ItemFilter k_LwsLabmeHuziCg_DzuzVoDiSfVVaKr;
 public static final ItemFilter KPiVqYSMfIiIGQeKCzmtSBitlmE_ttaT;
 public static final ItemFilter GjcvqldnMZTWIMBXbiWuT_gigoQPYRvU;
 public static final ItemFilter bFcsykWSEbslEvNrhmgfpLwIUoW_EaZY;
 public static final Vector2i PEcipTQIPeHhSmsSg_xLyxeFqiLLKVko;
 public static final Vector2i rxZZQRHkdidtnGaqjbqODdGhBlJIQpNZ;
 public static final Vector2i vecLj_tfimkGvDpdeYqkoNmcdBSHieAZ;
 public static final Vector2i PkPHVFTxUJSJGznztXZnwsOwwNenpqqd;
 public static final Vector2i YABduFlJixJpotUrifhDg_NkctEHzeRg;
 public static final int rgnxaqym_mizAXnZCAOVjXgjZGXtcBbz = 56;
 public static final int KRGARVWLkALMZtppynHvJiAlQpZrfRwM = 10;
 public static final Vector2i cVdJRJsfedRDvZcxZmFdBVQhyRwIHvLK;
 public static final Vector2i yJijQLxWqTnIP_HPnNppZVDnCqTliCjq;
 public static final RenderColor bBwsjgbwvYTRDktaIwXCLKdEiBCfSWca;
 public static final int tEWXXdscHgXQPuhzIthEBEuzKUiWQ_dB = 250;
 public static final int FqAWzbSssnkwkDOWmb_qCWcLx_ZpDBXX = 15;
 public static final int SHpsyONZCnBNTcPZr_ydOXikoPMBZIyQ = 6;
 public static final Vector2i HnxsPvcEhabnBQUjsGTqJdSRZUsonILz;
 public static final Vector2i NWmXtWFxnoAkEAtcdoTOzjwzbPYosxIB;
 public static final ItemFilter GldCxaMePcvWSEZF_kNMSbBYHLsFzRiT;
 public static final ItemFilter qxNnsxddMAsAvAtynCwUaRRwpqJStsIN;
 public static final ItemFilter zJaQsuYZWTAREIzwPwBUuwadMWCrAbrN;
 public static final ItemFilter ORYYpIynEaXCV_lQljCBMhdZNBsCtsMQ;
 public static final ItemFilter IlGNOtHemovZSPpuYMFVCwuqSHUUJOjG;
 public static final ItemFilter DVAQWDNXWrvFpScTNYroyvBENImZmNgS;
 public static final int _pTLsZbgOwAamDZKpFxMPmirdPeoSaWe = 305;
 public static final Vector2i WQFnbaFFHAQiBVwirePsKsAyPKxilsxr;
 public static final int EDhIWTmKTdApRVtLKVJ_gSVTkEkgSuqA = 7;
 public static final RenderColor pFrVPkhONVmsnQlOkOTUhRWlDTvDdbZs;
 public static final RenderColor XrZdPyhGYayiKDkMIJuKFSEswHWRwhSj;
 public static final Vector2i qXtqlcYmhtwsvAObrFxvxLryXvsEqcUx;
 public static final Vector2i Lvu_PbUusFUzZSiOlvWPLmtEDSRldPwQ;
 public static final RenderColor PkGYXYgKAoQMqzMXfGszhEmlRBOwUdIe;
 public static final RenderColor tLCBusAR_mKZJTrcwygyBEIeeb_UcaTI;
 public static final int FMbOWNjOiwOLpyQwleGTShCPbZiNzEoh = 29;
 public static final Vector2i j_FzqazTbMgQ_OYzZphHjmZAojudEzpy;
 public static final int GYCAadombvQhhoTbfGGccYvZViwepGhE = 22;
 public static final RenderColor EqvOgjiMDYHJsxsbxEtYimqLftQUsFGT;
 public static final RenderColor qthSqbfDiuPthwiQslUSNTvPKqnjLKnd;
 public static final RenderColor tYlujKosDWDfglqjFFYEUEQuFZpyEgnJ;
 public static final int kOnuLMmdadhitGrtMpfiNhoxNHeXGDdr = 65;
 public static final int cQeVzRIgRQykJqdtLfWSSoALelnUeiwk = 12;
 public static final int DGyWJwYFVbD_HXVyEzWvoQjWEWBqBmWs = 20;
 public static final int pRvnklsnzMNGbkKKqKYQrCQFcghTIKea = 72;
 public static final int VOzqeuGUAVtrfGemxpMCOMmZTCjYxBJN = 44;
 public static final int gRsyZRJSVzKhsRfMhTUEnSmmljPEcUnd = 41;
 public static final int glrrlRmZYgPwzcVxfnZdydorXqPAcRFm = 10;
 public static final int FDHzUFlnAgeIbMBqepjinBMibwMRfSbH = 16;
 public static final RenderColor uXaKDfDvWOvvlbRLgJICesGRIzVIiedS;
 public static final RenderColor FYuDlJYwlhHiirBPoWjLpKQGUSjfmszF;
 public static final int _DGnUgMLHAowNMBJEkyPRJOSfHCAReHY = 29;
 public static final int GHZdQBtmTeuQLJybgid_znVxQivsscBm = 223;
 public static final int iRvIDxuEqgjjCCOuTGcxaPVddgbRgjid = 29;
 public static final int gNbowrtNZCdBcZEKJufyprQqxwUq_nLj = 12;
 public static final int jVNOrFPmknusNJEdlHxGznEwJvwCzaRi = 4;
 public static final ItemFilter ZsbjaK_AszSUyXhIbTVZhkjkztAsommD;
 public static final int VIbyNspH_POUAROmOgDoNexDDVFAMAeT = 29;
 public static final Vector2i LCcLMtPtPqnZZresNEvoQrxMvtJCzwiW;
 public static final Vector2i IacBrX_STLBSdJjeiNmVttPaPvzFpyfR;
 public static final int dXaVqNsoV_bJepYJByyYHOFQyGxYlqQk = 43;
 public static final Vector2i snXCdnDJALjRELPsTDDJzoBwfWRrCKNs;
 public static final int MoApcvYdgCGnUNubtdHiBjlhpYkxSAly = 10;
 public static final Vector2i WxDYkbKW_RmHFhqv_RZqjspnATRFTVHH;
 public static final int RJNEWFKLNFxKAiojPDrTkAgNPFaVbBIL = 164;
 public static final int sVjtNwCTCYOGVyZOnpajjFfukeqKNxPC = 10;
 public static final Vector2i LoxuGSPDBCizC_xKCyromQPH_AjmCqvU;
 public static final int snEONFlbITUJgpYpndwUgLBIAuiegwUL = 12;
 public static final int GtdkhHfkOpvEDSBBqqjDEBlTXBSxzygw = 17;
 public static final int PpqViIUtNdZ_exYsuomumjgUxZSKLAay = 16;
 public static final int mHwsbFLYPgMnzbcVHEwTgpcesLAEfLkt = 12;
 public static final Vector2i bezQThwjfLfVylpfGOX_psdMmfIBGXda;
 public static final Vector2i QVkNxYdCFFGgEeMbcldcweaFnOoPfUXt;
 public static final RenderColor uxGnmNHgqHXlfDfwJUVsVgSyDbNKGYPj;
 public static final int BAwGoDsaJ_JgIggBjE_QqSxqunhPbCGg = 29;
 public static final int HAJyGIWmsiOEtzNQXVmGICwaxNkqxvYm = 35;
 public static final int TeIAmD_qZnkJYsVylXnsiHWSGUVBbDdO = 3;
 public static final RenderColor DOtNVGIgdhytyZbIsTCrVHpMFdHKFWWJ;
 public static final RenderColor mPYY_DKtMVyuRpeUAkxFusGFXgSLKfid;
 public static final Vector2i ETPPuzZGofsUbmTeCDGlZvlrpULyHnjS;
 public static final int qxlhVhJcJNKZusaCjqjZttGKtYXZQgmi = 56;
 public static final int YjQEKbvzSCFFJsyTnHodUVpARIznQdO_ = 41;
 public static final int uH_AkaLcJJtZdbQXFoWeBnKeeLsvBcQo = 46;
 public static final int MIcMifkWMpUlJ_iXfQqZEaYQfl_GkixB = 10;
 public static final int xZJTgDxWGuVuLqIcSYy_dz_opRmebWFE = 38;
 public static final int JnswwgOetpxacCBrrPbzybdhNPrVarfK = 10;
 public static final int hxFaCIQmbneCfmibVhHcwNjOkMLkNP_s = 4;
 public static final int lteZMWbviiFwobXoUZGkmntFVnysAvCx = 3;
 public static final RenderColor Uet_WAXtRmJLCswwqa_xfBtBqLcJQEuP;
 public static final int cbAFuIXHdhmeZnwHujGJtXiEqLfaUavX = 9;
 public static final int wlnrHJkeQfRxcXpZDZqLfUcsNqjzIbxS = 12;
 public static final int xWUuPrFcmUzUyQOE_CcCVwUgJQPkGQyC = 32;
 public static final RenderColor xbXDfJVmrGejnzjMBdnGRfTUlHQhBETd;
 public static final int NHzZkLctdYhgAhUesozanTeuf_tdNIsb = 10;
 public static final int CELKsEegVhlesCsPKyMCgMPytCAckwUf = 10;
 public static final Vector2i VKDNnmlObzdpciqBzWomdBsnJtCgFaoB;
 public static final int tpJhYdNysuRaOmraPIQpmBWVGPpjhDLf = 34;
 public static final int gWkEGoFvJpCMGbikqQAmoxeYgIrTAuGc = 5;
 public static final int cFndVUckrxwXJYHFNtpjhKVlyfippmls = 26;
 public static final int xFjeaEyfXhCcjrCXGVLBUllUoLtkdPQi = 5;
 public static final int tGLPLxXuYACYeyAwRrfyF_jHSBTnQFFa = 4;
 public static final int CFmYjqhVQkBKbcLwPqXtvAeCRmvUPzzg = 44;
 public static final int abTNWe_WxECDKCxoiPcHtCFjGdndLFEt = 112;
 public static final int VRBxbtyVwtdDVNLrv_PmytNfcWuahfoN = 124;
 public static final int FgSjtKZrxnynUgb_MmwKtdxxhHOQcrkQ = 124;
 public static final int BykQIHhvZrEuyyXFIxzsFczJdhmEnyxa = 94;
 public static final int Nn_AeLOkERCzZNwqlUxZfhdyIWltJpdT = 124;
 public static final Vector2i pdbAhfDeCEkbGvSwOIDJVPCTBtBMrLgM;
 public static final int traQjTGyySZcmhxkUghcFNkEdUPsTAgn = 38;
 public static final int jqPPbGYzjPQROijTVINZQltaDVYmWfVU = 10;
 public static final RenderColor LfVdinOqqkrAWUBndMqNvTYDBBVQj_Cu;
 public static final int hkxGgiGwnpwvxknmagASeY_dIr_uyQmE = 8;
 public static final int AJleEsjiNFtEnespzPHWjmlJxxPLf_sE = 3;
 public static final int jYcsuhNZVGDRDMxLDfqiMecVvOuGDbRy = 4;
 public static final int WfsavT_CcpwyV_kENXIKQAcxtEaPLbNQ = 222;
 public static final int XUhxaQJKElHCZsdSaRJCAjFRW_UYUABn = 41;
 public static final int bPkiNDQeRcJQ_vzKVvWIxuEjHNdohsNi = 105;
 public static final int ZinSqLqEonAKEBNiZkzJzuJnFVZarWAF = 128;
 public static final int QwxacSlkcvSORtnBPI_MZCsXiuvyMcuL = 195;
 public static final RenderColor smszVFxEZOOXQXrzgreXNVQHOKuXoGDI;

 private ItemUtils() {
 throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
 }

 static {
 yQgyRbzvArWXVsfxUvs_YEpFdAefcNVK = RenderColor.of((int)174, (int)0, (int)255, (int)255);
 NzqAeWuhxaEZfyWgCRKAyEUisjcGiStq = new Vector2i(852, 609);
 qLGiNZguIVWuYgukYQCVPuudbcUtMGCl = RenderColor.of((float)0.117f, (float)0.117f, (float)0.117f, (float)0.4f);
 zmVUyjYbuHQxDLnBwb_hxxL_kvTnlMma = RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.3f);
 kUeBudAektqsoWQaBmyIysBZrmaXRpRf = RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f);
 FoDFGMKsINYoeIDPZYrCXxCwrIuuKtWj = RenderColor.WHITE;
 xdAkggrqt_LXsmGOYIajCAYEaOZesRtP = new Vector2i(165, 35);
 TlqtoNNKbxBkzVvoNoaZUpYppoJpOlaX = new Vector2i(25, 19);
 m_sEbXCcekDevArDsotSNehErhobVWHN = new ItemFilter(RenderColor.WHITE, RenderColor.WHITE, RenderColor.of((int)235, (int)196, (int)255, (int)255), RenderColor.of((int)235, (int)196, (int)255, (int)255));
 tgJLPLRmNFSHcOjOrKFlKiCzMikowIOX = new Vector2i(292, 55);
 DFUWuaUujKjcvOENqGVMLjZiFBolTTYs = new Vector2i(20, 12);
 ctKTNGRtdSZideKETtxhftLMUGSisMoI = new ItemFilter(RenderColor.of((float)0.117f, (float)0.117f, (float)0.117f, (float)0.1f), RenderColor.of((float)0.117f, (float)0.117f, (float)0.117f, (float)0.1f), RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.2f), RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.2f));
 IyJncuwtlZNSFuDfXhQZURvAWjfa_PzS = new ItemFilter(zmVUyjYbuHQxDLnBwb_hxxL_kvTnlMma, RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE);
 a_lbOGSpCqNmwKlKXuzrovwerhFbmOyH = new ItemFilter(RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.8f), RenderColor.WHITE, RenderColor.WHITE, RenderColor.WHITE);
 k_LwsLabmeHuziCg_DzuzVoDiSfVVaKr = new ItemFilter(ItemUtils.ctKTNGRtdSZideKETtxhftLMUGSisMoI.bpFwNbQBCVBagxvnbFldIhYaotHRhXNu, ItemUtils.IyJncuwtlZNSFuDfXhQZURvAWjfa_PzS.bpFwNbQBCVBagxvnbFldIhYaotHRhXNu, ItemUtils.a_lbOGSpCqNmwKlKXuzrovwerhFbmOyH.bpFwNbQBCVBagxvnbFldIhYaotHRhXNu);
 KPiVqYSMfIiIGQeKCzmtSBitlmE_ttaT = new ItemFilter(ItemUtils.ctKTNGRtdSZideKETtxhftLMUGSisMoI.eVItyspIeiSXBShJWeDhAJMdiRNggpkj, ItemUtils.IyJncuwtlZNSFuDfXhQZURvAWjfa_PzS.eVItyspIeiSXBShJWeDhAJMdiRNggpkj, ItemUtils.a_lbOGSpCqNmwKlKXuzrovwerhFbmOyH.eVItyspIeiSXBShJWeDhAJMdiRNggpkj);
 GjcvqldnMZTWIMBXbiWuT_gigoQPYRvU = new ItemFilter(ItemUtils.ctKTNGRtdSZideKETtxhftLMUGSisMoI.gYjVc_DdHPWKYATSaVumNmO_wQKcEwYd, ItemUtils.IyJncuwtlZNSFuDfXhQZURvAWjfa_PzS.gYjVc_DdHPWKYATSaVumNmO_wQKcEwYd, ItemUtils.a_lbOGSpCqNmwKlKXuzrovwerhFbmOyH.gYjVc_DdHPWKYATSaVumNmO_wQKcEwYd);
 bFcsykWSEbslEvNrhmgfpLwIUoW_EaZY = new ItemFilter(ItemUtils.ctKTNGRtdSZideKETtxhftLMUGSisMoI.xVWojXhmgurRaaBQ_LAQCOyHnilPUwVJ, ItemUtils.IyJncuwtlZNSFuDfXhQZURvAWjfa_PzS.xVWojXhmgurRaaBQ_LAQCOyHnilPUwVJ, ItemUtils.a_lbOGSpCqNmwKlKXuzrovwerhFbmOyH.xVWojXhmgurRaaBQ_LAQCOyHnilPUwVJ);
 PEcipTQIPeHhSmsSg_xLyxeFqiLLKVko = new Vector2i(208, 64);
 rxZZQRHkdidtnGaqjbqODdGhBlJIQpNZ = new Vector2i(208, 458);
 vecLj_tfimkGvDpdeYqkoNmcdBSHieAZ = new Vector2i(638, 540);
 PkPHVFTxUJSJGznztXZnwsOwwNenpqqd = new Vector2i(208, 80);
 YABduFlJixJpotUrifhDg_NkctEHzeRg = new Vector2i(17, 12);
 cVdJRJsfedRDvZcxZmFdBVQhyRwIHvLK = new Vector2i(ItemUtils.YABduFlJixJpotUrifhDg_NkctEHzeRg.x + 56 + 8, ItemUtils.YABduFlJixJpotUrifhDg_NkctEHzeRg.y);
 yJijQLxWqTnIP_HPnNppZVDnCqTliCjq = new Vector2i(ItemUtils.YABduFlJixJpotUrifhDg_NkctEHzeRg.x + 56 + 8, ItemUtils.YABduFlJixJpotUrifhDg_NkctEHzeRg.y + 26);
 bBwsjgbwvYTRDktaIwXCLKdEiBCfSWca = RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f);
 HnxsPvcEhabnBQUjsGTqJdSRZUsonILz = new Vector2i(220, 35);
 NWmXtWFxnoAkEAtcdoTOzjwzbPYosxIB = new Vector2i(6, 3);
 GldCxaMePcvWSEZF_kNMSbBYHLsFzRiT = new ItemFilter(RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE, RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE);
 qxNnsxddMAsAvAtynCwUaRRwpqJStsIN = new ItemFilter(RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE, RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE);
 zJaQsuYZWTAREIzwPwBUuwadMWCrAbrN = new ItemFilter(new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RSKOOTLGyDIYckbDhKMyk_MrTQCrWG_a, ItemUtils.GldCxaMePcvWSEZF_kNMSbBYHLsFzRiT.bpFwNbQBCVBagxvnbFldIhYaotHRhXNu, ItemUtils.qxNnsxddMAsAvAtynCwUaRRwpqJStsIN.bpFwNbQBCVBagxvnbFldIhYaotHRhXNu), new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RSKOOTLGyDIYckbDhKMyk_MrTQCrWG_a, ItemUtils.GldCxaMePcvWSEZF_kNMSbBYHLsFzRiT.gYjVc_DdHPWKYATSaVumNmO_wQKcEwYd, ItemUtils.qxNnsxddMAsAvAtynCwUaRRwpqJStsIN.gYjVc_DdHPWKYATSaVumNmO_wQKcEwYd), new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RSKOOTLGyDIYckbDhKMyk_MrTQCrWG_a, ItemUtils.GldCxaMePcvWSEZF_kNMSbBYHLsFzRiT.eVItyspIeiSXBShJWeDhAJMdiRNggpkj, ItemUtils.qxNnsxddMAsAvAtynCwUaRRwpqJStsIN.eVItyspIeiSXBShJWeDhAJMdiRNggpkj), new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RSKOOTLGyDIYckbDhKMyk_MrTQCrWG_a, ItemUtils.GldCxaMePcvWSEZF_kNMSbBYHLsFzRiT.xVWojXhmgurRaaBQ_LAQCOyHnilPUwVJ, ItemUtils.qxNnsxddMAsAvAtynCwUaRRwpqJStsIN.xVWojXhmgurRaaBQ_LAQCOyHnilPUwVJ));
 ORYYpIynEaXCV_lQljCBMhdZNBsCtsMQ = new ItemFilter(RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE, RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE);
 IlGNOtHemovZSPpuYMFVCwuqSHUUJOjG = new ItemFilter(RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE, RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE);
 DVAQWDNXWrvFpScTNYroyvBENImZmNgS = new ItemFilter(new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RaH__tCKslYaJPBCDQnqGypzHABhxCee, ItemUtils.ORYYpIynEaXCV_lQljCBMhdZNBsCtsMQ.bpFwNbQBCVBagxvnbFldIhYaotHRhXNu, ItemUtils.IlGNOtHemovZSPpuYMFVCwuqSHUUJOjG.bpFwNbQBCVBagxvnbFldIhYaotHRhXNu), new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RaH__tCKslYaJPBCDQnqGypzHABhxCee, ItemUtils.ORYYpIynEaXCV_lQljCBMhdZNBsCtsMQ.gYjVc_DdHPWKYATSaVumNmO_wQKcEwYd, ItemUtils.IlGNOtHemovZSPpuYMFVCwuqSHUUJOjG.gYjVc_DdHPWKYATSaVumNmO_wQKcEwYd), new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RaH__tCKslYaJPBCDQnqGypzHABhxCee, ItemUtils.ORYYpIynEaXCV_lQljCBMhdZNBsCtsMQ.eVItyspIeiSXBShJWeDhAJMdiRNggpkj, ItemUtils.IlGNOtHemovZSPpuYMFVCwuqSHUUJOjG.eVItyspIeiSXBShJWeDhAJMdiRNggpkj), new ItemFilter(BTHACK$$$C_eFRkRXTIulbQsVUcIwGtGmowywIOmYNodSrAmssqVzFgcrasbLmBzAfOqmiCcV.YAxWDkwCOdwaxrDJ_LfdXXoMqBADadKF.RaH__tCKslYaJPBCDQnqGypzHABhxCee, ItemUtils.ORYYpIynEaXCV_lQljCBMhdZNBsCtsMQ.xVWojXhmgurRaaBQ_LAQCOyHnilPUwVJ, ItemUtils.IlGNOtHemovZSPpuYMFVCwuqSHUUJOjG.xVWojXhmgurRaaBQ_LAQCOyHnilPUwVJ));
 WQFnbaFFHAQiBVwirePsKsAyPKxilsxr = new Vector2i(305, 50);
 pFrVPkhONVmsnQlOkOTUhRWlDTvDdbZs = kUeBudAektqsoWQaBmyIysBZrmaXRpRf;
 XrZdPyhGYayiKDkMIJuKFSEswHWRwhSj = FoDFGMKsINYoeIDPZYrCXxCwrIuuKtWj;
 qXtqlcYmhtwsvAObrFxvxLryXvsEqcUx = new Vector2i(305, 422);
 Lvu_PbUusFUzZSiOlvWPLmtEDSRldPwQ = new Vector2i(20, 12);
 PkGYXYgKAoQMqzMXfGszhEmlRBOwUdIe = RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.3f);
 tLCBusAR_mKZJTrcwygyBEIeeb_UcaTI = RenderColor.of((float)0.0f, (float)0.0f, (float)0.0f, (float)0.4f);
 j_FzqazTbMgQ_OYzZphHjmZAojudEzpy = new Vector2i(48, 18);
 EqvOgjiMDYHJsxsbxEtYimqLftQUsFGT = tLCBusAR_mKZJTrcwygyBEIeeb_UcaTI;
 qthSqbfDiuPthwiQslUSNTvPKqnjLKnd = yQgyRbzvArWXVsfxUvs_YEpFdAefcNVK;
 tYlujKosDWDfglqjFFYEUEQuFZpyEgnJ = RenderColor.WHITE;
 uXaKDfDvWOvvlbRLgJICesGRIzVIiedS = RenderColor.WHITE;
 FYuDlJYwlhHiirBPoWjLpKQGUSjfmszF = kUeBudAektqsoWQaBmyIysBZrmaXRpRf;
 ZsbjaK_AszSUyXhIbTVZhkjkztAsommD = new ItemFilter(RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.7f), RenderColor.WHITE, RenderColor.of((int)208, (int)124, (int)255, (int)255), RenderColor.of((int)232, (int)185, (int)255, (int)255));
 LCcLMtPtPqnZZresNEvoQrxMvtJCzwiW = new Vector2i(38, 22);
 IacBrX_STLBSdJjeiNmVttPaPvzFpyfR = new Vector2i(362, 209);
 snXCdnDJALjRELPsTDDJzoBwfWRrCKNs = new Vector2i(10, 3);
 WxDYkbKW_RmHFhqv_RZqjspnATRFTVHH = new Vector2i(38, 21);
 LoxuGSPDBCizC_xKCyromQPH_AjmCqvU = new Vector2i(140, 140);
 bezQThwjfLfVylpfGOX_psdMmfIBGXda = new Vector2i(30, 140);
 QVkNxYdCFFGgEeMbcldcweaFnOoPfUXt = new Vector2i(14, 2);
 uxGnmNHgqHXlfDfwJUVsVgSyDbNKGYPj = kUeBudAektqsoWQaBmyIysBZrmaXRpRf;
 DOtNVGIgdhytyZbIsTCrVHpMFdHKFWWJ = kUeBudAektqsoWQaBmyIysBZrmaXRpRf;
 mPYY_DKtMVyuRpeUAkxFusGFXgSLKfid = FoDFGMKsINYoeIDPZYrCXxCwrIuuKtWj;
 ETPPuzZGofsUbmTeCDGlZvlrpULyHnjS = new Vector2i(398, 502);
 Uet_WAXtRmJLCswwqa_xfBtBqLcJQEuP = RenderColor.of((float)0.0f, (float)0.0f, (float)0.0f, (float)0.3f);
 xbXDfJVmrGejnzjMBdnGRfTUlHQhBETd = RenderColor.of((float)1.0f, (float)1.0f, (float)1.0f, (float)0.5f);
 VKDNnmlObzdpciqBzWomdBsnJtCgFaoB = new Vector2i(10, 4);
 pdbAhfDeCEkbGvSwOIDJVPCTBtBMrLgM = new Vector2i(382, 168);
 LfVdinOqqkrAWUBndMqNvTYDBBVQj_Cu = RenderColor.of((int)30, (int)30, (int)30, (int)102);
 smszVFxEZOOXQXrzgreXNVQHOKuXoGDI = RenderColor.of((float)0.35f, (float)0.35f, (float)1.0f, (float)0.5f);
 }
}

